import { connectMongoDB } from "./mongodb";
import { Course, Project } from "./models";

const coursesData = [
  {
    title: "The Complete JavaScript Course 2024",
    description: "Master JavaScript with the most complete course! Projects, challenges, quizzes, ES6+, OOP, AJAX, Webpack, and more.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/the-complete-javascript-course/",
    instructor: "Jonas Schmedtmann",
    duration: "69 hours",
    level: "Beginner",
    skills: ["JavaScript", "ES6+", "OOP", "DOM Manipulation", "Async/Await"],
    isFree: false,
    rating: "4.7",
  },
  {
    title: "CS50: Introduction to Computer Science",
    description: "Harvard's introduction to computer science and the art of programming. Learn C, Python, SQL, and web development.",
    platform: "edX",
    url: "https://www.edx.org/course/cs50s-introduction-to-computer-science",
    instructor: "David J. Malan",
    duration: "12 weeks",
    level: "Beginner",
    skills: ["C", "Python", "SQL", "Algorithms", "Data Structures"],
    isFree: true,
    rating: "4.9",
  },
  {
    title: "React - The Complete Guide",
    description: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and more!",
    platform: "Udemy",
    url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
    instructor: "Maximilian Schwarzmuller",
    duration: "48 hours",
    level: "Intermediate",
    skills: ["React", "Redux", "React Router", "Hooks", "Next.js"],
    isFree: false,
    rating: "4.6",
  },
  {
    title: "Python for Everybody Specialization",
    description: "Learn to program and analyze data with Python. Develop programs to gather, clean, analyze, and visualize data.",
    platform: "Coursera",
    url: "https://www.coursera.org/specializations/python",
    instructor: "Dr. Charles Severance",
    duration: "8 months",
    level: "Beginner",
    skills: ["Python", "Data Structures", "Web Scraping", "Databases", "Data Visualization"],
    isFree: true,
    rating: "4.8",
  },
  {
    title: "Machine Learning by Stanford",
    description: "Learn machine learning from the fundamentals. Understand algorithms, neural networks, and how to apply ML to real problems.",
    platform: "Coursera",
    url: "https://www.coursera.org/learn/machine-learning",
    instructor: "Andrew Ng",
    duration: "11 weeks",
    level: "Intermediate",
    skills: ["Machine Learning", "Python", "Neural Networks", "Linear Regression", "Clustering"],
    isFree: true,
    rating: "4.9",
  },
  {
    title: "Node.js, Express, MongoDB & More",
    description: "Master Node by building a real-world RESTful API and web app with authentication, Node.js security, and payments.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
    instructor: "Jonas Schmedtmann",
    duration: "42 hours",
    level: "Intermediate",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs", "Authentication"],
    isFree: false,
    rating: "4.8",
  },
  {
    title: "freeCodeCamp Full Stack Web Development",
    description: "Learn HTML, CSS, JavaScript, React, Node.js, and more through interactive coding challenges and projects.",
    platform: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn/",
    instructor: "freeCodeCamp",
    duration: "300+ hours",
    level: "Beginner",
    skills: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
    isFree: true,
    rating: "4.7",
  },
  {
    title: "AWS Certified Solutions Architect",
    description: "Prepare for the AWS Solutions Architect Associate exam. Learn cloud architecture, EC2, S3, VPC, and more.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
    instructor: "Stephane Maarek",
    duration: "27 hours",
    level: "Intermediate",
    skills: ["AWS", "Cloud Computing", "EC2", "S3", "VPC", "IAM"],
    isFree: false,
    rating: "4.7",
  },
  {
    title: "Docker and Kubernetes: The Complete Guide",
    description: "Build, test, and deploy Docker applications with Kubernetes while learning production-style development workflows.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    instructor: "Stephen Grider",
    duration: "22 hours",
    level: "Intermediate",
    skills: ["Docker", "Kubernetes", "CI/CD", "DevOps", "Container Orchestration"],
    isFree: false,
    rating: "4.6",
  },
  {
    title: "SQL for Data Science",
    description: "Learn SQL basics for data science and analytics. Query databases and perform data analysis with real datasets.",
    platform: "Coursera",
    url: "https://www.coursera.org/learn/sql-for-data-science",
    instructor: "Sadie St. Lawrence",
    duration: "4 weeks",
    level: "Beginner",
    skills: ["SQL", "Data Analysis", "Database Management", "Data Filtering"],
    isFree: true,
    rating: "4.6",
  },
  {
    title: "TypeScript Essential Training",
    description: "Learn TypeScript fundamentals and advanced features. Build type-safe applications with modern TypeScript.",
    platform: "YouTube",
    url: "https://www.youtube.com/watch?v=BwuLxPH8IDs",
    instructor: "Academind",
    duration: "3.5 hours",
    level: "Beginner",
    skills: ["TypeScript", "Type Safety", "Interfaces", "Generics", "Decorators"],
    isFree: true,
    rating: "4.8",
  },
  {
    title: "The Complete Web Developer Bootcamp",
    description: "Learn web development from scratch including HTML, CSS, JavaScript, Node, React, MongoDB, and more.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/the-web-developer-bootcamp/",
    instructor: "Colt Steele",
    duration: "63 hours",
    level: "Beginner",
    skills: ["HTML", "CSS", "JavaScript", "Node.js", "Express", "MongoDB"],
    isFree: false,
    rating: "4.7",
  },
  {
    title: "Git and GitHub Crash Course",
    description: "Learn Git version control from basics to advanced. Master branching, merging, and collaborating on GitHub.",
    platform: "YouTube",
    url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    instructor: "freeCodeCamp",
    duration: "1 hour",
    level: "Beginner",
    skills: ["Git", "GitHub", "Version Control", "Branching", "Collaboration"],
    isFree: true,
    rating: "4.9",
  },
  {
    title: "System Design Interview Course",
    description: "Prepare for system design interviews at top tech companies. Learn to design scalable distributed systems.",
    platform: "YouTube",
    url: "https://www.youtube.com/c/SystemDesignInterview",
    instructor: "System Design Interview",
    duration: "20+ hours",
    level: "Advanced",
    skills: ["System Design", "Distributed Systems", "Scalability", "Load Balancing", "Caching"],
    isFree: true,
    rating: "4.7",
  },
  {
    title: "Data Structures and Algorithms in Python",
    description: "Master data structures and algorithms with Python. Prepare for coding interviews at top companies.",
    platform: "Udemy",
    url: "https://www.udemy.com/course/data-structures-algorithms-python/",
    instructor: "Scott Barrett",
    duration: "9 hours",
    level: "Intermediate",
    skills: ["Data Structures", "Algorithms", "Python", "Problem Solving", "Big O Notation"],
    isFree: false,
    rating: "4.7",
  },
];

const projectsData = [
  {
    title: "Personal Portfolio Website",
    description: "Build a responsive portfolio website to showcase your projects and skills. Implement modern CSS layouts and animations.",
    difficulty: "Easy",
    skills: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    githubUrl: "https://github.com/topics/portfolio-website",
    phase: "Beginner",
    estimatedTime: "1-2 weeks",
  },
  {
    title: "Todo Application with Local Storage",
    description: "Create a fully functional todo app with CRUD operations. Learn DOM manipulation and browser storage APIs.",
    difficulty: "Easy",
    skills: ["JavaScript", "DOM Manipulation", "Local Storage", "CSS"],
    githubUrl: "https://github.com/topics/todo-app",
    phase: "Beginner",
    estimatedTime: "1 week",
  },
  {
    title: "Weather Dashboard",
    description: "Build a weather app that fetches real-time data from a weather API. Display forecasts and current conditions.",
    difficulty: "Easy",
    skills: ["JavaScript", "REST APIs", "Async/Await", "CSS"],
    githubUrl: "https://github.com/topics/weather-app",
    phase: "Beginner",
    estimatedTime: "1-2 weeks",
  },
  {
    title: "Blog Platform with React",
    description: "Create a blog application with React. Implement routing, state management, and a clean user interface.",
    difficulty: "Medium",
    skills: ["React", "React Router", "State Management", "CSS-in-JS"],
    githubUrl: "https://github.com/topics/react-blog",
    phase: "Intermediate",
    estimatedTime: "3-4 weeks",
  },
  {
    title: "E-commerce Product Page",
    description: "Build a responsive e-commerce product page with image gallery, cart functionality, and dynamic pricing.",
    difficulty: "Medium",
    skills: ["React", "State Management", "CSS", "UX Design"],
    githubUrl: "https://github.com/topics/ecommerce",
    phase: "Intermediate",
    estimatedTime: "2-3 weeks",
  },
  {
    title: "Full-Stack Task Manager",
    description: "Create a task management app with user authentication, teams, and real-time updates using WebSockets.",
    difficulty: "Medium",
    skills: ["Node.js", "Express", "MongoDB", "React", "Authentication"],
    githubUrl: "https://github.com/topics/task-manager",
    phase: "Intermediate",
    estimatedTime: "4-6 weeks",
  },
  {
    title: "RESTful API with Express",
    description: "Design and build a RESTful API with proper routing, middleware, validation, and error handling.",
    difficulty: "Medium",
    skills: ["Node.js", "Express", "REST APIs", "MongoDB", "JWT"],
    githubUrl: "https://github.com/topics/rest-api",
    phase: "Intermediate",
    estimatedTime: "2-3 weeks",
  },
  {
    title: "Chat Application with Socket.io",
    description: "Build a real-time chat application with multiple rooms, private messaging, and online status indicators.",
    difficulty: "Medium",
    skills: ["Node.js", "Socket.io", "React", "MongoDB", "Real-time Communication"],
    githubUrl: "https://github.com/topics/chat-application",
    phase: "Intermediate",
    estimatedTime: "3-4 weeks",
  },
  {
    title: "Machine Learning Image Classifier",
    description: "Train a convolutional neural network to classify images. Deploy the model with a web interface.",
    difficulty: "Hard",
    skills: ["Python", "TensorFlow", "CNNs", "Flask", "Machine Learning"],
    githubUrl: "https://github.com/topics/image-classification",
    phase: "Advanced",
    estimatedTime: "4-6 weeks",
  },
  {
    title: "Microservices Architecture Project",
    description: "Design and implement a microservices-based application with Docker, Kubernetes, and service mesh.",
    difficulty: "Hard",
    skills: ["Docker", "Kubernetes", "Microservices", "Node.js", "Message Queues"],
    githubUrl: "https://github.com/topics/microservices",
    phase: "Advanced",
    estimatedTime: "6-8 weeks",
  },
  {
    title: "Data Pipeline and Dashboard",
    description: "Build an ETL pipeline to process and analyze data. Create interactive visualizations with a dashboard.",
    difficulty: "Hard",
    skills: ["Python", "SQL", "Data Engineering", "Airflow", "Data Visualization"],
    githubUrl: "https://github.com/topics/data-pipeline",
    phase: "Advanced",
    estimatedTime: "4-6 weeks",
  },
  {
    title: "CI/CD Pipeline Setup",
    description: "Configure a complete CI/CD pipeline with automated testing, building, and deployment to cloud platforms.",
    difficulty: "Hard",
    skills: ["GitHub Actions", "Docker", "AWS/GCP", "Testing", "DevOps"],
    githubUrl: "https://github.com/topics/cicd",
    phase: "Advanced",
    estimatedTime: "2-3 weeks",
  },
  {
    title: "Social Media Clone",
    description: "Build a full-featured social media platform with posts, followers, notifications, and real-time features.",
    difficulty: "Hard",
    skills: ["React", "Node.js", "MongoDB", "Redis", "GraphQL"],
    githubUrl: "https://github.com/topics/social-network",
    phase: "Advanced",
    estimatedTime: "8-12 weeks",
  },
  {
    title: "CLI Tool with Node.js",
    description: "Create a command-line tool that automates a common development task. Publish it to npm.",
    difficulty: "Easy",
    skills: ["Node.js", "CLI Development", "npm", "JavaScript"],
    githubUrl: "https://github.com/topics/cli-app",
    phase: "Beginner",
    estimatedTime: "1-2 weeks",
  },
  {
    title: "Chrome Extension",
    description: "Build a browser extension that enhances web browsing. Learn the extension API and popup interfaces.",
    difficulty: "Medium",
    skills: ["JavaScript", "Chrome API", "HTML", "CSS"],
    githubUrl: "https://github.com/topics/chrome-extension",
    phase: "Intermediate",
    estimatedTime: "2-3 weeks",
  },
];

export async function seedMongoDB() {
  try {
    await connectMongoDB();

    const existingCourses = await Course.countDocuments();
    if (existingCourses === 0) {
      console.log("Seeding courses...");
      await Course.insertMany(coursesData);
      console.log(`Seeded ${coursesData.length} courses`);
    } else {
      console.log(`Courses already seeded (${existingCourses} found)`);
    }

    const existingProjects = await Project.countDocuments();
    if (existingProjects === 0) {
      console.log("Seeding projects...");
      await Project.insertMany(projectsData);
      console.log(`Seeded ${projectsData.length} projects`);
    } else {
      console.log(`Projects already seeded (${existingProjects} found)`);
    }

    console.log("Database seeding complete!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

